services:
  server:
    build: 
      context: ${SERVER_DIR}
      args:
        - PORT=${SERVER_PORT}
        - BASE_IMAGE=python:3.14-trixie

  ui:
    build:
      context: ${UI_DIR}
      args:
        - PORT=${UI_PORT}
        - BASE_IMAGE=oven/bun:1
        - PUBLIC_BACKEND_URL=http://server:${SERVER_PORT}
    environment:
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=ui

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
