services:
  db:
    image: mirror.gcr.io/postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: stop
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} # FIXME: this needs to be a secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    image: server
    build: 
      context: ${SERVER_DIR}
      args:
        - PORT=${SERVER_PORT}
        - BASE_IMAGE=mirror.gcr.io/python:3.14-trixie
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@db:5432/stop
    depends_on:
      - db

  ui:
    image: ui
    build:
      context: ${UI_DIR}
      args:
        - PORT=${UI_PORT}
        - BASE_IMAGE=mirror.gcr.io/oven/bun:1
    environment:
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=ui
    depends_on:
      - server

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - ssl_key
      - ssl_pem
    depends_on:
      - server
      - ui

volumes:
  postgres_data: {}

secrets:
  ssl_key:
    file: ./stop.key
  ssl_pem:
    file: ./stop.pem
