events { }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    limit_req_zone $binary_remote_addr zone=default:10m rate=10r/s;

    server {
        limit_req zone=default burst=12 delay=8;

        listen 80;

        location /api {
            proxy_pass http://server:3000;
        }

        location / {
            proxy_pass http://ui:8080;
        }
    }
}
